import Header from "@/components/ui/header";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const JetBrains_MonoFont = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800"],
  variable: '--font-jetbrainsMono'
});



export const metadata = {
  title: "ShanuKa Dilshan's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className= {JetBrains_MonoFont.variable}>
        <Header/>

        
        {children}
      </body>
    </html>
  );
}
